apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: maros-tessera-job
  namespace: maros-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: maros-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: https://github.com/RositsaKrasteva/blockchain-automation-framework.git
    ref: feature-386
  values:
    metadata:
      name: maros-tessera-job
      namespace: maros-quo    
    image:      
      repository: quorumengineering/tessera:21.4.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: quorummaros
      role: vault-role
      serviceaccountname: vault-auth
      tmprefix: secret/maros-quo/crypto/maros/transaction
