---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tessera-config-{{ .Values.node.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: tessera-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  tessera-config.json.tmpl: |-
    {
      "useWhiteList": "false",
      "jdbc": {
        "username": {{ .Values.tessera.dbusername | quote }},
        "password": "",
        "url": {{ .Values.tessera.dburl | quote }}
      },
      "serverConfigs": [
        {
          "app": "ThirdParty",
          "enabled": true,
          "serverAddress": "http://{{ .Values.node.name }}-tessera:9080",
          "communicationType": "REST"
        },
        {
          "app": "Q2T",
          "enabled": true,
          "serverAddress": {{ .Values.tessera.clienturl | quote }},          
          "sslConfig": {
            "tls": {{ .Values.tessera.tls | quote }},
            "generateKeyStoreIfNotExisted": true,
            "serverKeyStore": "{{ .Values.node.mountPath }}/tm/tessera_cer.key",
            "serverTlsCertificatePath": "{{ .Values.node.mountPath }}/tm/tessera_cer.pem",
            "serverTrustCertificates": ["{{ .Values.node.mountPath }}/tm/tessera_ca.pem"],
            "clientTrustMode": {{ .Values.tessera.trust | quote }},
            "clientTlsKeyPath": "{{ .Values.node.mountPath }}/tm/tessera_cer.key",
            "clientTlsCertificatePath": "{{ .Values.node.mountPath }}/tm/tessera_cer.pem",
            "clientTrustCertificates": ["{{ .Values.node.mountPath }}/tm/tessera_ca.pem"],
            "knownClientsFile": "{{ .Values.node.mountPath }}/tm/known_client1",
            "knownServersFile": "{{ .Values.node.mountPath }}/tm/known_server1",
            "clientAuth": true
          },
          "communicationType": "REST"
        },
        {
          "app": "P2P",
          "enabled": true,
          "serverAddress": {{ .Values.tessera.url | quote }},
          "sslConfig": {
            "tls": {{ .Values.tessera.tls | quote }},
            "generateKeyStoreIfNotExisted": true,
            "serverTrustMode": {{ .Values.tessera.trust | quote }},
            "serverTlsKeyPath": "{{ .Values.node.mountPath }}/tm/tessera_cer.key",
            "serverTlsCertificatePath": "{{ .Values.node.mountPath }}/tm/tessera_cer.pem",
            "serverTrustCertificates": ["{{ .Values.node.mountPath }}/tm/tessera_ca.pem"],            
            "clientTrustMode": {{ .Values.tessera.trust | quote }},
            "clientTlsKeyPath": "{{ .Values.node.mountPath }}/tm/tessera_cer.key",
            "clientTlsCertificatePath": "{{ .Values.node.mountPath }}/tm/tessera_cer.pem",
            "clientTrustCertificates": ["{{ .Values.node.mountPath }}/tm/tessera_ca.pem"],
            "knownClientsFile": "{{ .Values.node.mountPath }}/tm/known_client2",
            "knownServersFile": "{{ .Values.node.mountPath }}/tm/known_server2"
          },
          "communicationType": "REST"
        }
      ],
      "peer": {{ .Values.tessera.othernodes | toPrettyJson | indent 6 }},
      "keys": {
        "passwords": [],
        "keyData": [
          {
           "privateKeyPath": "%THIS_PRIV_KEY%",
           "publicKeyPath": "%THIS_PUB_KEY%"
          }
        ]
      },
      "alwaysSendTo": []
    }